# Generated by Django 4.0.1 on 2022-01-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
    ]
